apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    template: postgresql-persistent-template
  name: postgresql
spec:
  accessMode:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi